### ISSUE TITLE
Error: Cannot batch space with type `<class 'gym.spaces.box.Box'>`. The space must be a valid `gymnasium.Space` instance.

### ISSUE THREAD

**Issue by sunchipsster1** [Achronus/rl_atari_games#5]
Hello! Wonderful repository for playing with montezuma's revenge with an algorithm that works! :) :) 

I am having a little bit of trouble getting it to run. After installing everything, I am running python main.py and get the following error: **_was wondering if you have seen this before?_** 

Thanks so much in advance :) 

/home/.conda/envs/rlatari/lib/python3.10/site-packages/gymnasium/vector/utils/spaces.py", line 49, in batch_space
    raise ValueError(
ValueError: Cannot batch space with type `<class 'gym.spaces.box.Box'>`. The space must be a valid `gymnasium.Space` instance.

.

For further info, here is my pip list: 
ale-py                     0.8.0
asttokens                  2.1.0
attrs                      22.1.0
AutoROM                    0.4.2
AutoROM.accept-rom-license 0.4.2
backcall                   0.2.0
brotlipy                   0.7.0
certifi                    2022.9.24
cffi                       1.15.1
charset-normalizer         2.0.4
click                      8.1.3
cloudpickle                2.2.0
cryptography               38.0.1
cycler                     0.11.0
decorator                  4.4.2
executing                  1.2.0
fonttools                  4.38.0
gym                        0.26.2
gym-notices                0.0.8
Gymnasium                  0.26.3
gymnasium-notices          0.0.1
idna                       3.4
imageio                    2.22.4
imageio-ffmpeg             0.4.7
importlib-resources        5.10.0
iniconfig                  1.1.1
ipython                    8.4.0
jedi                       0.18.1
kiwisolver                 1.4.4
lz4                        4.0.2
matplotlib                 3.5.1
matplotlib-inline          0.1.6
mkl-fft                    1.3.1
mkl-random                 1.2.2
mkl-service                2.4.0
moviepy                    1.0.3
numpy                      1.22.4
opencv-python              4.6.0.66
packaging                  21.3
parso                      0.8.3
PettingZoo                 1.22.2
pexpect                    4.8.0
pickleshare                0.7.5
Pillow                     9.2.0
pip                        22.2.2
pluggy                     1.0.0
proglog                    0.1.10
prompt-toolkit             3.0.32
ptyprocess                 0.7.0
pure-eval                  0.2.2
py                         1.11.0
pycparser                  2.21
pygame                     2.1.2
Pygments                   2.13.0
pymunk                     6.2.1
pyOpenSSL                  22.0.0
pyparsing                  3.0.9
PySocks                    1.7.1
pytest                     7.1.2
python-dateutil            2.8.2
PyYAML                     6.0
requests                   2.28.1
setuptools                 65.5.0
six                        1.16.0
stack-data                 0.6.1
SuperSuit                  3.7.0
tinyscaler                 1.2.5
tomli                      2.0.1
torch                      1.12.0
torchaudio                 0.12.0
torchvision                0.13.0
tqdm                       4.64.1
traitlets                  5.5.0
typing_extensions          4.3.0
urllib3                    1.26.12
wcwidth                    0.2.5
wheel                      0.37.1

**Comment by Achronus** [comment]
Hey @sunchipsster1 ,

Thanks for your interest in this repository.

It appears the issue relates to OpenAI's recent update of the Gym package to Gymnasium. I've added a quick hotfix to accommodate compatibility changes. Unfortunately, fixing this issue has caused me to encounter a new one with the PyTorch package -  `RuntimeError: Numpy is not available`. 

It's likely this is only a local issue (I hope), but I am currently updating all my packages (especially PyTorch) which should resolve the new issue. The hotfix only applies to one file: `core/env_details.py` -> [here](https://github.com/Achronus/rl_atari_games/blob/main/core/env_details.py).

Additionally, I've made minor changes to the `main.py` file to simplify it.

While I'm updating the packages, can you please apply the new hotfix and see if things work on your end? The best option would be to copy the new `core/env_details.py` into the old one and go from there. Let me know if you encounter any more issues :)

Ryan

**Comment by Achronus** [comment]
Hey @sunchipsster1,

As a follow up on my previous comment, I've updated the repository to fix the broken compatibility issues. Everything should now be working as intended. Please update your packages to the latest ones as detailed in the dependencies section of the README and the requirements.txt file.

Let me know if you have any further issues.

Many thanks.

Ryan

**Comment by sunchipsster1** [comment]
@Achronus thank you so much! It runs and I am training now on the default parameters (with create_model = rainbow, of course). 

Fingers crossed :)

**Comment by sunchipsster1** [comment]
Hi @Achronus just wanted to confirm that I am doing as you had originally intended - I have only modified main.py by one line: 
    model = create_model('ppo', env='primary', device=device) --> into     **model = create_model('rainbow', env=env3, device=device)**

I've left the other hyperparameters as they were. 

For 3 different seeds, currentlyrunning around ~~ (40.0K/100K) episodes,  the Episode Score is still at 0. Would love to get the beautiful results that you obtained in your baseline. Am I making an unforeseen error?

**Comment by Achronus** [comment]
Hey @sunchipsster1,

That's normal behaviour for agents in complex environments. It's known as a 'burn-in' period, where the agent is still learning the environment dynamics. Typically, its length varies depending on the model and the environment's complexity. The more complex the environment, the longer the burn-in period. For example, with an A2C algorithm, I created for Super Mario Bros, the burn-in period lasted around 110k-120k episodes before it finally figured out how to jump longer and get over a large pipe.  

I haven't had the opportunity (yet) to explore the full extent of RDQNs, so the parameters are not optimised. The best advice I can offer:
1. Refer to the original paper's hyperparameters in the appendix - [Rainbow: Combining Improvements in Deep Reinforcement Learning](https://arxiv.org/abs/1710.02298). Their approach is extremely computationally expensive, requiring a buffer size of 1 million. Typically, this is unfeasible on standard computer hardware.
2. Experiment with the parameters yourself to find ones that work for your hypothesis. For example, how many episodes will it take to reach the first key (reward signal)? 
3. Enable curiosity to improve agent exploration - 
`model = create_model('rainbow', env=env3, device=device, im_type='curiosity')`

What makes Montezuma's so challenging is the sparse rewards and the vast state space. The agent needs to identify a specific movement pattern to reach the first reward and then continue from there. Solving the environment as a whole is a fascinating problem, requiring a lot of small steps. 

Sorry, I can't be of more help.

Ryan
